// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission06_allipope.Models;

namespace mission06_allipope.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission06_allipope.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Documetary"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Romantic Comedy"
                        });
                });

            modelBuilder.Entity("mission06_allipope.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryID = 1,
                            Director = "Taika Watiti",
                            Edited = false,
                            Rating = "pg13",
                            Title = "Hunt for the Wilderpeople",
                            Year = (short)2016
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryID = 3,
                            Director = "Nancy Meyers",
                            Edited = false,
                            Rating = "pg13",
                            Title = "The Intern",
                            Year = (short)2015
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryID = 5,
                            Director = "Phyllida Lloyd",
                            Edited = false,
                            Rating = "pg13",
                            Title = "Mamma Mia!",
                            Year = (short)2008
                        });
                });

            modelBuilder.Entity("mission06_allipope.Models.MovieResponse", b =>
                {
                    b.HasOne("mission06_allipope.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
